# PBS flags
queue: normal
project: e14 
walltime: 5:00:00
ncpus: 1477
mem: 3840GB
jobname: WomNP_wp2_74

collate:
  walltime: 4:00:00
  mem: 128GB
  ncpus: 16
  queue: express

# Model config:
model: mom
shortpath: /scratch/e14/
exe: fms_MOM_SIS_Wombat_Jun2020.x
input: 
    - /g/data/v45/pas561/mom/input/wombat_jun16z_input
    - /g/data/v45/pas561/mom/input/wombat_jun16z_bgc_sbc
    - /g/data/v45/pas561/mom/input/wombat_masks

restart: /g/data3/v45/pas561/mom/archive/wombat_jun16z/restart2020

# Misc
stacksize: unlimited
